steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-t', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA', 
           '-f', 'build/Dockerfile', 
           '--target', 'prod', 
           '.']
  
  # イメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA']
  
  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-backend'
      - '--image=gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=USE_LOCAL_DB=false,RUN_HOT_RELOAD=false'
      - '--port=8080'

images:
  - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
