steps:
  # 環境変数ファイルを処理して適用するステップ
  - name: 'bash'
    id: 'prepare-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # prob.envから変数をロード
        echo "Loading environment variables from build/env/prob.env"
        ENV_VARS=$(grep -v '^#' build/env/prob.env | tr '\n' ',' | sed 's/,$//')
        echo "ENV_VARS=$ENV_VARS" > /workspace/env_vars.txt
  
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA', '-f', 'build/Dockerfile', '--target', 'prod', '.']
  
  # イメージをプッシュするステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA']
  
  # Cloud Runにデプロイ (前のステップで生成した変数を使用)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env_vars.txt
        gcloud run deploy portfolio-backend \
          --image=gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA \
          --region=asia-northeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="$ENV_VARS" \
          --update-secrets="POSTGRES_PASSWORD=POSTGRES_PASSWORD:latest,SUPABASE_KEY=SUPABASE_KEY:latest" \
          --port=8080

# GitHub Actionsから渡される変数
substitutions:
  _POSTGRES_PASSWORD: ""
  _SUPABASE_URL: ""
  _SUPABASE_KEY: ""

images:
  - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'
  