steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA', '-f', 'build/Dockerfile', '--target', 'prod', '.']
  
  # イメージをプッシュするステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA']
  
  # 環境変数ファイルを処理してデプロイするステップ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Loading environment variables from build/env/prob.env"
        
        # 環境変数を読み込んでenvs.txtに保存（直接変数として使わない）
        grep -v '^#' build/env/prob.env > /workspace/envs.txt
        
        # envs.txtから--set-env-varsフラグ用の形式を作成
        ENV_FLAGS=""
        while IFS= read -r line; do
          if [[ ! -z "$line" ]]; then
            ENV_FLAGS="${ENV_FLAGS}${line},"
          fi
        done < /workspace/envs.txt
        ENV_FLAGS=${ENV_FLAGS%,}  # 末尾のカンマを削除
        
        echo "Deploying with environment variables: $ENV_FLAGS"
        
        # 環境変数とシークレットを設定してデプロイ
        gcloud run deploy portfolio-backend \
          --image=gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA \
          --region=asia-northeast1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="$ENV_FLAGS" \
          --update-secrets="POSTGRES_PASSWORD=POSTGRES_PASSWORD:latest,SUPABASE_KEY=SUPABASE_KEY:latest" \
          --port=8080

images:
  - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY