steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA', '-f', 'build/Dockerfile', '--target', 'prod', '.']
  
  # イメージをプッシュするステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA']
  
  # スクリプトに実行権限を付与
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'chmod +x ./deploy.sh']
  
  # スクリプトを実行してデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: './build/scripts/deploy.sh'
    args: ['gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY