steps:
  # substitutesの値を表示
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'echo "COMMIT_SHA: ${_COMMIT_SHA}" && echo "POSTGRES_PASSWORD_B64: ${_POSTGRES_PASSWORD_B64::10}" && echo "SUPABASE_KEY_B64: ${_SUPABASE_KEY_B64::10}" && echo "SUPABASE_URL_B64: ${_SUPABASE_URL_B64::10}"']
  
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA', '-f', 'build/Dockerfile', '--target', 'prod', '.']
  
  # イメージをプッシュするステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA']
  
  # スクリプトに実行権限を付与
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'chmod +x ./build/scripts/gcr_deploy.sh']
  
  # スクリプトを実行してデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: './build/scripts/gcr_deploy.sh'
    args: ['gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA', '${_POSTGRES_PASSWORD_B64}', '${_SUPABASE_KEY_B64}', '${_SUPABASE_URL_B64}']

images:
  - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'

# 置換変数の明示的な宣言
substitutions:
  _COMMIT_SHA: "a"
  _POSTGRES_PASSWORD_B64: "b"
  _SUPABASE_KEY_B64: "c"
  _SUPABASE_URL_B64: "d"

options:
  logging: CLOUD_LOGGING_ONLY
