version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: portfolio_dev
    ports:
      - "8080:8080"
    env_file:
      - build/env/dev.env
    volumes:
      # ホットリロード用 (開発時のみ)
      - ./:/src:ro
    restart: unless-stopped
    networks:
      - app-network
    profiles: ["dev"]

  app-main:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: portfolio_main
    ports:
      - "8080:8080"
    env_file:
      - build/env/main.env
    restart: unless-stopped
    networks:
      - app-network
    profiles: ["main"]

  db-dev:
    image: postgres:14
    container_name: portfolio_tools_hub_db_dev
    env_file:
      - build/env/dev.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["dev"]

  db-main:
    image: postgres:14
    container_name: portfolio_tools_hub_db_main
    env_file:
      - build/env/main.env
    volumes:
      - postgres_data_main:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["main"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_dev:
  postgres_data_main: