name: Test and Trigger Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: '1.24'
        
    # - name: Run Tests
    #   run: go test ./... -v
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1.1.1'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    # Cloud Buildトリガー
    - name: Trigger Cloud Build
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # シークレットの先頭部分をデバッグ表示（セキュリティのため全体は表示しない）
        echo "PASSWORD: ${#POSTGRES_PASSWORD} chars | KEY: ${#SUPABASE_KEY} chars | URL: $SUPABASE_URL"
    
        gcloud builds submit --config=cloudbuild.yaml \
          --substitutions="_POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}",_SUPABASE_URL="${{ secrets.SUPABASE_URL }}",_SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}"
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}