name: Test and Trigger Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: '1.24'
        
    # - name: Run Tests
    #   run: go test ./... -v
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1.1.1'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # デバッグ用に変数の確認    
    - name: 'Check environment variables'
      run: |
        echo "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD::10}"
        echo "SUPABASE_KEY: ${SUPABASE_KEY::10}"
        echo "SUPABASE_URL: ${SUPABASE_URL::10}"
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        
    # Cloud Buildトリガー
    - name: Trigger Cloud Build
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # コミットSHAの取得
        COMMIT_SHA=$(git rev-parse HEAD)
        echo "COMMIT_SHA: $COMMIT_SHA"

        # 一時ファイルを作成（ディレクトリ作成）
        TEMP_DIR=$(mktemp -d)
        
        # 変数をファイルに書き込む（改行なしで直接保存）
        echo -n "${{ secrets.POSTGRES_PASSWORD }}" > $TEMP_DIR/password.txt
        echo -n "${{ secrets.SUPABASE_KEY }}" > $TEMP_DIR/key.txt
        echo -n "${{ secrets.SUPABASE_URL }}" > $TEMP_DIR/url.txt
        
        # ファイルをBase64エンコード
        POSTGRES_PWD=$(base64 -w0 $TEMP_DIR/password.txt)
        SUPABASE_KEY=$(base64 -w0 $TEMP_DIR/key.txt)
        SUPABASE_URL=$(base64 -w0 $TEMP_DIR/url.txt)
        
        # 変数値の確認（デバッグ用・機密情報は表示しない）
        echo "Encoded password length: ${#POSTGRES_PWD}"
        echo "Encoded key length: ${#SUPABASE_KEY}"
        echo "Encoded URL length: ${#SUPABASE_URL}"
        
        # 変数をファイルとして保存
        echo $COMMIT_SHA > $TEMP_DIR/commit.txt
        echo $POSTGRES_PWD > $TEMP_DIR/pwd_b64.txt
        echo $SUPABASE_KEY > $TEMP_DIR/key_b64.txt
        echo $SUPABASE_URL > $TEMP_DIR/url_b64.txt
        
        # ファイルから変数を読み込んでCloud Buildに渡す
        gcloud builds submit --config=cloudbuild.yaml \
          --substitutions=_COMMIT_SHA="$(cat $TEMP_DIR/commit.txt)",_POSTGRES_PASSWORD_B64="$(cat $TEMP_DIR/pwd_b64.txt)",_SUPABASE_KEY_B64="$(cat $TEMP_DIR/key_b64.txt)",_SUPABASE_URL_B64="$(cat $TEMP_DIR/url_b64.txt)"
        
        # 一時ファイルの削除
        rm -rf $TEMP_DIR
