name: Test and Trigger Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: '1.24'
        
    # - name: Run Tests
    #   run: go test ./... -v
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1.1.1'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # デバッグ用に変数の確認    
    - name: 'Check environment variables'
      run: |
        echo "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD::10}"
        echo "SUPABASE_KEY: ${SUPABASE_KEY::10}"
        echo "SUPABASE_URL: ${SUPABASE_URL::10}"
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        
    # Cloud Buildトリガー
    - name: Trigger Cloud Build
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # コミットSHAの取得
        COMMIT_SHA=$(git rev-parse HEAD)
        echo "COMMIT_SHA: $COMMIT_SHA"

        # Base64エンコードして特殊文字の問題を回避
        POSTGRES_PWD_B64=$(echo -n "${{ secrets.POSTGRES_PASSWORD }}" | base64)
        SUPABASE_KEY_B64=$(echo -n "${{ secrets.SUPABASE_KEY }}" | base64)
        SUPABASE_URL_B64=$(echo -n "${{ secrets.SUPABASE_URL }}" | base64)
        
        # デバッグ用にエンコードした値の先頭10文字を表示
        echo "POSTGRES_PASSWORD_B64: ${POSTGRES_PWD_B64::10}"
        echo "SUPABASE_KEY_B64: ${SUPABASE_KEY_B64::10}"
        echo "SUPABASE_URL_B64: ${SUPABASE_URL_B64::10}"
        
        # エンコードした値をCloud Buildに渡す
        gcloud builds submit --config=cloudbuild.yaml \
          --substitutions=_COMMIT_SHA="$COMMIT_SHA",_POSTGRES_PASSWORD_B64="$POSTGRES_PWD_B64",_SUPABASE_KEY_B64="$SUPABASE_KEY_B64",_SUPABASE_URL_B64="$SUPABASE_URL_B64"
